### ISSUE TITLE
building a reactive Plotly output bar chart for direction/same city/never found

### ISSUE THREAD

**Issue by skrivulskaya** [skrivulskaya/ministerial-elopements#12]
Trying the build a Plotly output that spits out direction information by replicating the steps Mat used to build the original directions table. The basic example is what I'd like the plot to look like is here, under "Basic Bar Chart" - https://plot.ly/r/bar-charts/ 
See lines 370 through 378 in the updated app.R
The error it spits out right now is "First argument, `data`, must be a data frame or shared data." 
How do I make the reactive direction information into a data frame?

**Comment by msisk1** [comment]
Crap. Closed the wrong issue.

**Comment by msisk1** [comment]
Fixed it. I think it was largely because plotly needs a table as a data frame. I also made it so the y axis always stays the same regardless of what the current maximum is. We can change that if need be.
