### ISSUE TITLE
publishing to shinyapps.io

### ISSUE THREAD

**Issue by skrivulskaya** [skrivulskaya/ministerial-elopements#13]
I'm getting an error when trying to publish the current version of the app to shinyapps.io.
Ideas as to what might be causing the problem?

**Comment by msisk1** [comment]
For whatever reason, shinyaps.io does not play well with the syntax I usually use for loading a list of packages:
packages<- c("rgdal", "leaflet", "shiny", "geosphere", "dygraphs", "dplyr", "ggplot2",
 "xts", "plotly", "DT", "crosstalk", "datasets", "shinyWidgets", "shinydashboard")
lapply(packages, require, character.only=T)

instead, it needs them to be loaded individually
library(rgdal)
library(leaflet)
library(shiny)
library(geosphere)
library(dygraphs)
etc...
