### ISSUE TITLE
Make the filter text prettier

### ISSUE THREAD

**Issue by msisk1** [skrivulskaya/ministerial-elopements#8]
Like a code box? Look at some examples.

**Comment by skrivulskaya** [comment]
This is the UI I used in the previous version of the dygraph tab for the text:
verbatimTextOutput("dygraph_description")

**Comment by skrivulskaya** [comment]
Mat, small issue: see the attached screenshot (when "Baptist" is selected)
![screen shot 2018-03-15 at 6 08 59 pm](https://user-images.githubusercontent.com/23707079/37493654-0faf6854-287c-11e8-993c-cd2f85454517.png)

**Comment by msisk1** [comment]
Fixed. Added a space and a comma
